# Generated by Django 4.2.11 on 2025-05-08 19:06

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.linestring
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('st_address_1', models.CharField(max_length=100, null=True)),
                ('st_address_2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('zip_code', models.CharField(max_length=5, null=True)),
                ('footprint', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=3857)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('method', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('notes', models.CharField(max_length=5000, null=True)),
                ('start_t', models.DateTimeField(default=django.utils.timezone.now)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.building')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_width', models.FloatField(default=20)),
                ('peak_capacity', models.IntegerField(default=0)),
                ('routing_id', models.CharField(max_length=255, null=True)),
                ('first_t', models.DateTimeField()),
                ('last_t', models.DateTimeField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=1)),
                ('velocity', models.FloatField(default=0)),
                ('t', models.DateTimeField()),
                ('current_segment', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=10)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=3857)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.network')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('wall_distance', models.FloatField(default=0)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(default=django.contrib.gis.geos.linestring.LineString([]), srid=4326)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_node', to='simulator.networknode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_node', to='simulator.networknode')),
            ],
        ),
        migrations.AddField(
            model_name='network',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.scenario'),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esri_id', models.CharField(max_length=100, null=True)),
                ('long_name', models.CharField(max_length=100, null=True)),
                ('short_name', models.CharField(max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=3857)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.building')),
            ],
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='EvacRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(default=django.contrib.gis.geos.linestring.LineString([]), srid=4326)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.network')),
            ],
        ),
        migrations.CreateModel(
            name='EvacGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=1)),
                ('evac_time', models.DateTimeField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esri_id', models.CharField(max_length=100, null=True)),
                ('use_type', models.CharField(max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=3857)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.level')),
            ],
        ),
        migrations.CreateModel(
            name='Barrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.scenario')),
            ],
        ),
    ]
