# Generated by Django 4.2.11 on 2025-05-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
