# Generated by Django 4.2.11 on 2025-05-09 20:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_level_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='footprint',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857),
        ),
        migrations.AlterField(
            model_name='building',
            name='st_address_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='st_address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
