# Generated by Django 4.2.11 on 2025-05-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_tag_alter_scenario_name_alter_scenario_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='simulation_status',
            field=models.CharField(blank=True, default='None', max_length=10),
        ),
    ]
