# Generated by Django 4.2.11 on 2025-05-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0005_scenario_simulation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacroute',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='edit_lock',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
