# Generated by Django 4.2.11 on 2025-05-16 01:40

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.linestring
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_evacroute_valid_scenario_edit_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkedge',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(default=django.contrib.gis.geos.linestring.LineString([]), srid=3857),
        ),
    ]
